### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by buiawpkgew1** [maboloshi/github-chinese#10]
1小时变成1月前![image](https://user-images.githubusercontent.com/71136405/215048098-cd92ee0e-8067-41c6-b9a1-f55f9797cf62.png)

**Comment by maboloshi** [comment]
事实上是 分钟和月 对应的英文缩略 全是 `m`🤣

**Comment by buiawpkgew1** [comment]
🤣

**Comment by buiawpkgew1** [comment]
为啥
![image](https://user-images.githubusercontent.com/71136405/215049283-a27e5a50-5645-48e0-a76e-f1162ce63333.png)
是在https://github.com/maboloshi/Blog/issues 里交bug？

**Comment by maboloshi** [comment]
?? 我没设置过 你用哪个源的

**Comment by maboloshi** [comment]
后续 我直接设置`@supportURL`好了

**Comment by buiawpkgew1** [comment]
> ?? 我没设置过 你用哪个源的

[github 托管](https://maboloshi.github.io/github-chinese/main.user.js)

**Comment by maboloshi** [comment]
> 为啥 ![image](https://user-images.githubusercontent.com/71136405/215049283-a27e5a50-5645-48e0-a76e-f1162ce63333.png) 是在https://github.com/maboloshi/Blog/issues 里交bug？

已修正 c5fcd891f5874f0f7a4df039fd896f323af64248

**Comment by buiawpkgew1** [comment]
> 事实上是 分钟和月 对应的英文缩略 全是 `m`🤣

所以这个能修复吗？

**Comment by maboloshi** [comment]
> > 事实上是 分钟和月 对应的英文缩略 全是 `m`🤣
> 
> 所以这个能修复吗？

后期 我想想办法吧 目前, 暂时不打算修复

**Comment by fbstorm** [comment]
日期就不用翻译了吧，有点英语水平都能知道对应的缩写是什么

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/219825209-3c441893-63de-4920-b5c2-59c915be0f15.png)
部分没汉化

**Comment by john2022wick** [comment]
> 事实上是 分钟和月 对应的英文缩略 全是 `m`🤣

我刚发现这个问题，正准备提交bug，就看见这里
鬼佬把分钟和月都叫`m`雀食让人头秃，这个真不好搞

**Comment by yige-yigeren** [comment]
> > > 事实上是 分钟和月 对应的英文缩略 全是 `m`🤣
> > 
> > 
> > 所以这个能修复吗？
> 
> 后期 我想想办法吧 目前, 暂时不打算修复

要不跳过日期？都用github action了不至于看不懂吧（）

或者这个地方强制翻译为分钟，因为最长只允许运行6小时

**Comment by wuyuncheng-26** [comment]
搞错关闭原因了😂

**Comment by yige-yigeren** [comment]
> 搞错关闭原因了😂

不改了吗

**Comment by wuyuncheng-26** [comment]
> > 搞错关闭原因了😂
> 
> 不改了吗

可能暂时改不了，我去看看吧

**Comment by maboloshi** [comment]
使用 #146 的方法 这个问题貌似不使用正则，也自然解决了

**Comment by maboloshi** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/7850715/7b2a11f8-1785-432f-949f-970343187b7f)
此处的问题吗，使用 #146 能解决

![image](https://github.com/maboloshi/github-chinese/assets/7850715/6eba0d3b-9cf8-4637-84b7-aabb7d9a7ef1)
这处待观察

**Comment by wuyuncheng-26** [comment]
已找到此问题的解决方案
不过目前此功能尚未合并到主分支
可以去 [`Test_zh-CN_LangEnvSet`](https://github.com/maboloshi/github-chinese/tree/Test_zh-CN_LangEnvSet) 分支下的 [`main.user.js`](https://github.com/maboloshi/github-chinese/raw/Test_zh-CN_LangEnvSet/main.user.js) 进行体验
