### ISSUE TITLE
未翻译的文本

### ISSUE THREAD

**Issue by kndxhz** [maboloshi/github-chinese#101]
![image](https://github.com/maboloshi/github-chinese/assets/113306265/4cdc2472-efa3-4955-96f1-a9ad96987b43)
_在翻你们自己的翻译js的时候突然发现上面的行数和github的《广告》没被翻译_
**我认为你们应该不会犯这么低级的错误，请问是有什么不翻译的原因吗**

**Comment by wuyuncheng-26** [comment]
我看看
发一下未翻译网址

**Comment by wuyuncheng-26** [comment]
有些网页是我们故意避开的，不是低级错误

**Comment by wuyuncheng-26** [comment]
刚刚图片没加载出来
现在看到了

**Comment by wuyuncheng-26** [comment]
找到了
![image](https://github.com/maboloshi/github-chinese/assets/122529705/b424ce77-a854-4007-8cb7-1364ddf6dac7)
![image](https://github.com/maboloshi/github-chinese/assets/122529705/b3b90d80-0144-498f-b5c5-d5688e9cdf06)

**Comment by maboloshi** [comment]
fix a475e5343db8bfee19c09197339febeda08716c4
