### ISSUE TITLE
疑似未翻译的文本

### ISSUE THREAD

**Issue by XiYanzx** [maboloshi/github-chinese#103]
此处文本没有翻译，是否是没必要翻译的内容？
![image](https://github.com/maboloshi/github-chinese/assets/122631685/c65fc409-1ea4-4e93-aa1d-23a6bf7b7c27)

**Comment by wuyuncheng-26** [comment]
额……

**Comment by wuyuncheng-26** [comment]
有没有种可能
我们没遇到过这种情况
甚至不知道怎么调出来

**Comment by XiYanzx** [comment]
啊...这也太奇葩了

**Comment by maboloshi** [comment]
https://github.com/maboloshi/github-chinese/blob/a475e5343db8bfee19c09197339febeda08716c4/locals.js#L1526-L1527

```js
            // 顶部提醒
            "You unlocked new Achievements with private contributions! ": "您通过私人贡献解锁了新成就！",
            "Show them off by including private contributions in your Profile in": "通过在您的个人资料中包含私人贡献来展示它们。",
```


不确定是不是叹号后多了个空格，还是现在2句合并1句了

下次更新我去掉这个多余的空格

**Comment by wuyuncheng-26** [comment]
@XiYanzx

**Comment by XiYanzx** [comment]
> https://github.com/maboloshi/github-chinese/blob/a475e5343db8bfee19c09197339febeda08716c4/locals.js#L1526-L1527
> 
> ```js
>             // 顶部提醒
>             "You unlocked new Achievements with private contributions! ": "您通过私人贡献解锁了新成就！",
>             "Show them off by including private contributions in your Profile in": "通过在您的个人资料中包含私人贡献来展示它们。",
> ```
> 
> 不确定是不是叹号后多了个空格，还是现在2句合并1句了
> 
> 下次更新我去掉这个多余的空格

那...更新一下试试呗？如果好了那就完美了

**Comment by sanbei101** [comment]
**我也遇到了,体验确实割裂了一点,修复了就更完美啦**

**Comment by maboloshi** [comment]
Fix c6e1534a793ac9b607c60550afd63eeed1e56f48

**Comment by wuyuncheng-26** [comment]
已修复
