### ISSUE TITLE
Bug，翻译在错误的句段被引用

### ISSUE THREAD

**Issue by gbostock** [maboloshi/github-chinese#104]
<img width="664" alt="屏幕截图 2024-02-05 184819" src="https://github.com/maboloshi/github-chinese/assets/94212663/c169e6d7-fca9-4686-ae5d-822a3b639f8f">

**Comment by wuyuncheng-26** [comment]
这个没办法……

**Comment by maboloshi** [comment]
我这么貌似没这个问题
![image](https://github.com/maboloshi/github-chinese/assets/7850715/21d8d0f4-de2e-4d11-8fed-90b7e3b089fe)

**Comment by gbostock** [comment]
在release页面没这个问题，加了星推到主页就有这个问题了，有点奇怪

**Comment by maboloshi** [comment]
规则已找到，正在测试是否有副作用
`reIgnoreClass`规则: `markdown-body`

**Comment by TC999** [comment]
其实没必要修，毕竟汉化用久了原来是啥都忘记了

**Comment by wuyuncheng-26** [comment]
有必要的
