### ISSUE TITLE
编辑代码时，代码中的 . 被替换为 。

### ISSUE THREAD

**Issue by YinCQL** [maboloshi/github-chinese#105]
<img width="920" alt="{3FADA863-A244-4ffe-B1BA-B75F5EBA0AD9}" src="https://github.com/maboloshi/github-chinese/assets/71113782/558e69ac-1b6e-494d-9ae7-4447b857e540">
已在开发版，发布版两个版本中测试，均出现以上情况

**Comment by YinCQL** [comment]
以下是代码片段
  if (ver === "-1")
    return Promise.all(
      readdirSync("InputData")
        .filter((v) => statSync(`InputData/${v}`).isDirectory())
        .map((v) => convertFile(v))
    )

  if (!existsSync(`InputData/${ver}`)) {
    console.log("Missing input data.")
    return
  }

**Comment by YinCQL** [comment]
`  if (ver === "-1")
    return Promise.all(
      readdirSync("InputData")
        .filter((v) => statSync(`InputData/${v}`).isDirectory())
        .map((v) => convertFile(v))
    )

  if (!existsSync(`InputData/${ver}`)) {
    console.log("Missing input data.")
    return
  }`

**Comment by wuyuncheng-26** [comment]
这个可能现在没办法解决，以后可能会添加区域限制

**Comment by wuyuncheng-26** [comment]
https://github.com/maboloshi/github-chinese/issues/89#issuecomment-1858789484
暂时的解决方案

**Comment by YinCQL** [comment]
> [#89 (comment)](https://github.com/maboloshi/github-chinese/issues/89#issuecomment-1858789484) 暂时的解决方案

好的，感谢

**Comment by wuyuncheng-26** [comment]
我先关闭议题了
