### ISSUE TITLE
议题里评论的时间有时候不翻译

### ISSUE THREAD

**Issue by fengzyf** [maboloshi/github-chinese#117]
测试网址：https://github.com/maboloshi/github-chinese/issues/7

在谷歌浏览器版本 122.0.6261.129，新建标签页，打开上面网址，多试几次，就会出现评论的时间不翻译。

![image](https://github.com/maboloshi/github-chinese/assets/154897680/30b225af-a5e6-4744-9027-c10a12282907)

**Comment by wuyuncheng-26** [comment]
嗯？还真是
可能是日期翻译被动了

**Comment by wuyuncheng-26** [comment]
似乎现在没这个错误了
