### ISSUE TITLE
发行版部分翻译语句不通顺

### ISSUE THREAD

**Issue by QianFuv** [maboloshi/github-chinese#124]
![PixPin_2024-04-04_12-23-14](https://github.com/maboloshi/github-chinese/assets/111696321/e0372c2a-b48b-49ca-831c-a59903424096)
![PixPin_2024-04-04_12-23-42](https://github.com/maboloshi/github-chinese/assets/111696321/10ec7511-d7cc-44cc-85d3-ccb9f2032dac)

**Comment by QianFuv** [comment]
正则功能导致的

**Comment by maboloshi** [comment]
Fix 9d1206b81df5044aa93c6ba6f48e9eb022924eae
