### ISSUE TITLE
使用Github新代码视图（beta 版本）后代码部分也被汉化

### ISSUE THREAD

**Issue by a76yyyy** [maboloshi/github-chinese#13]
[使用新代码视图（beta 版本）](https://docs.github.com/zh/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view)

**Comment by kasuganosoras** [comment]
测试存在同样问题，所有的英文句号 `.` 都被翻译为了中文句号 `。`
![image](https://user-images.githubusercontent.com/34357771/222520862-4eef032e-2357-4821-bd1c-826af5643357.png)
