### ISSUE TITLE
仓库文件代码内容被翻译怎么配置取消这部分的翻译

### ISSUE THREAD

**Issue by quanlook** [maboloshi/github-chinese#130]
1. 怎么取消仓库内代码内容翻译

![image](https://github.com/maboloshi/github-chinese/assets/49576053/72ea80ab-b3e9-4504-aa27-5d5f7d33fc40)

- 代码内容标点符号被翻译

![image](https://github.com/maboloshi/github-chinese/assets/49576053/08282f32-f040-4ba1-8c4f-53f696b1bd7f)

- 代码内容被翻译

![image](https://github.com/maboloshi/github-chinese/assets/49576053/9f675844-de07-4aeb-83e8-15a08292fe2d)

**Comment by maboloshi** [comment]
目前，静态查看模式下是正常的。动态编辑模式下还有问题。

**Comment by wuyuncheng-26** [comment]
> 1. 怎么取消仓库内代码内容翻译
> 
> ![image](https://private-user-images.githubusercontent.com/49576053/325871206-72ea80ab-b3e9-4504-aa27-5d5f7d33fc40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjg3NzgsIm5iZiI6MTcxNDEyODQ3OCwicGF0aCI6Ii80OTU3NjA1My8zMjU4NzEyMDYtNzJlYTgwYWItYjNlOS00NTA0LWFhMjctNWQ1ZjdkMzNmYzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNmFmNzNmMzIyM2M4MTEwZGY4YjA2ZWYzODM0NTI1MThiODAyZTk4ZWEwMzBiNThjYzFlYmFjMjk1ZTZkNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.roMw6ZWvahoiCAmhKBkHi-cCNlwds3SXdt8aDvNkGEw)
> 
> * 代码内容标点符号被翻译
> 
> ![image](https://private-user-images.githubusercontent.com/49576053/325871503-08282f32-f040-4ba1-8c4f-53f696b1bd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjg3NzgsIm5iZiI6MTcxNDEyODQ3OCwicGF0aCI6Ii80OTU3NjA1My8zMjU4NzE1MDMtMDgyODJmMzItZjA0MC00YmExLThjNGYtNTNmNjk2YjFiZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMGRhZmU2MmJjNTRjMDU0NTQzNjI1YTY2ZTUwN2RkNWNiNGRkYzhiZmI1ZTM4NWJkMDU5NjlhZjBlMmQzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqWy1xpofC_zKyvSepzczKGmpY9rLdoZsqx6OOgtT9k)
> 
> * 代码内容被翻译
> 
> ![image](https://private-user-images.githubusercontent.com/49576053/325871654-9f675844-de07-4aeb-83e8-15a08292fe2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjg3NzgsIm5iZiI6MTcxNDEyODQ3OCwicGF0aCI6Ii80OTU3NjA1My8zMjU4NzE2NTQtOWY2NzU4NDQtZGUwNy00YWViLTgzZTgtMTVhMDgyOTJmZTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmVhMTNmNGQ0NDdjNzdlMDZjYjU0ZDA5YmYwMzkzMDA0NjdiNWIyMDQ2YTU0MTE5YzI2MjVmMGYzMWVhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGVC33q5TsZbqBBI9XDwP4u2DIxhn2ld0OlEMOAvHTc)

这个恐怕没办法，要去做class检测，类似这里
![image](https://github.com/maboloshi/github-chinese/assets/122529705/5bda1626-fdad-4c9a-b9dd-30b1c3e06126)

**Comment by wuyuncheng-26** [comment]
暂时的解决方法：动态编辑模式下关闭脚本

**Comment by wuyuncheng-26** [comment]
https://github.com/maboloshi/github-chinese/issues/89#issuecomment-1858789484
这个解决方案可以试一下

**Comment by maboloshi** [comment]
测试版中基本修复
