### ISSUE TITLE
是否可以使用Userscript(macOS/iOS)?

### ISSUE THREAD

**Issue by xycabcd** [maboloshi/github-chinese#136]
试了一下不管事，什么原因，怎么让他管事？（自己改代码可以接受）

**Comment by wuyuncheng-26** [comment]
![IMG_5915](https://github.com/maboloshi/github-chinese/assets/122529705/7a0b4c68-73ae-4d6e-9b3d-bfdb115ab4f8)
我这里是可以的 没有改代码

**Comment by xycabcd** [comment]
你这个不是Userscript, 是Stay
Userscript 是这个
![Userscript图标](https://github.com/maboloshi/github-chinese/assets/145047708/535b2e42-08e2-4a42-9cef-4df5dfde4f93)

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/122529705/b139bf27-087f-4475-84fb-29642322fa0f)
请看文档
Userscript 尚未测试

**Comment by xycabcd** [comment]
是哪些地方不行啊。有没有人说一句哪些地方用的这些软件的专有接口啊

**Comment by wuyuncheng-26** [comment]
我们没做测试

**Comment by maboloshi** [comment]
没有测试环境

**Comment by xycabcd** [comment]
> 没有测试环境

Userscript是免费的

**Comment by xycabcd** [comment]
如果能适配，感激不尽

**Comment by xycabcd** [comment]
为啥Macaque是"Safari UserScript Manager for iOS, iPadOS and macOS", 手机端还要弄个Stay,支持作者吗？

**Comment by xycabcd** [comment]
$1.99???这么贵

**Comment by maboloshi** [comment]
说实话 macOS和iOS、iPadOS 下兼容性我们没环境测试。@xycabcd 您不妨测试一下，反馈上来

**Comment by xycabcd** [comment]
没搞过这方面开发，不知道怎么测
