### ISSUE TITLE
希望增加鼠标放到日期相关上面的时候改为中文日期格式

### ISSUE THREAD

**Issue by C-racker** [maboloshi/github-chinese#137]

**Comment by wuyuncheng-26** [comment]
您的意思是……？

**Comment by wuyuncheng-26** [comment]
日期目前是自动翻译的，您是希望改成鼠标指针放在上面后翻译？

**Comment by C-racker** [comment]
> 日期目前是自动翻译的，您是希望改成鼠标指针放在上面后翻译？ ![image](https://private-user-images.githubusercontent.com/122529705/333777920-4432b84c-e54b-4f68-9c88-2db2d632d036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTk1NjgsIm5iZiI6MTcxNjYxOTI2OCwicGF0aCI6Ii8xMjI1Mjk3MDUvMzMzNzc3OTIwLTQ0MzJiODRjLWU1NGItNGY2OC05Yzg4LTJkYjJkNjMyZDAzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwNjQxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDkwNDlkNjk5NWE4NGYzZWNkNmVjZGViYTMwZjZlOTc0ZDc1ZDBkYWY4YjFjMDUzM2Q0YjY0MTgxN2EyNzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b6GBgHkk23rUj7iEolFVX0ltmr1eqir7U5IzjKqLhpU)

<img width="967" alt="image" src="https://github.com/maboloshi/github-chinese/assets/20217449/0729ca2a-7efd-48ea-812d-47c7c2a7f481">

这里的日期

**Comment by C-racker** [comment]
建议格式化为 2024-05-25 14:47:19 这样的

**Comment by wuyuncheng-26** [comment]
这个就有点违反**翻译**的原则了吧
这个日期本就是**标准化**的

**Comment by maboloshi** [comment]
想要这样的效果？
![屏幕截图 2024-05-25 162948](https://github.com/maboloshi/github-chinese/assets/7850715/e2c8ee44-59a8-4e78-9c74-f767d1888c64)

**Comment by wuyuncheng-26** [comment]
aha 应该是这样的

**Comment by wuyuncheng-26** [comment]
@C-racker

**Comment by cosing** [comment]
似乎简单的设置 relative-time 的lang就能做到这一点，如下
（只是一个简单示例没关心效率，我完全没怎么学过js
```js
function formatTime(timeStr) {
  return timeStr.slice(0, 19);
}

function funa(mutations) {
  // 更新所有已存在的 <relative-time> 元素
  var times = document.getElementsByTagName('relative-time');
  for (var i = 0; i < times.length; i++) {
    times[i].setAttribute('lang', "zh")
  }
};

(function () {
  var observer = new MutationObserver(funa);

  // 监听 <body> 元素的变化
  observer.observe(document.body, {
    childList: true,
    subtree: true
  });
})();
```
事实上我并不喜欢中文化时间，我想要纯数字时间，但是似乎得调整很多[属性](https://github.com/github/relative-time-element/tree/main?tab=readme-ov-file#attributes)，算了中文也差不多。

大脑升级梗图.jpg
```js
(function() {
 document.documentElement.lang = 'zh';
})();
```
似乎直接这样更改也可以达到效果。但是我不确定副作用影响（运行时机建议为document-start）

**Comment by cosing** [comment]
事实上 GitHub官方是支持了多语言时间的，只是因为默认没使用中文环境罢了。

https://github.com/github/relative-time-element/blob/4b5442f0816ffb9c0f525cdd798a945c346aea9a/examples/index.html#L166-L186

**Comment by maboloshi** [comment]
目前，我使用一个函数`formatTime`在处理时间元素时读取`datetime`, 并使用`toLocaleString('zh-CN')`转换格式, 使用`setAttribute`赋值到`title`.

函数放到`traverseNode`的翻译时间元素过程中

**Comment by maboloshi** [comment]
目前使用
```js
(function() {
 document.documentElement.lang = 'zh';
})();
```
效果如下
<img width="398" alt="image" src="https://github.com/maboloshi/github-chinese/assets/7850715/3d17db75-6e3a-4afa-a815-90c2b169b7d8">

**Comment by wuyuncheng-26** [comment]
大家转移到 #146 讨论吧

**Comment by wuyuncheng-26** [comment]
目前此功能尚未合并到主分支
可以去 [`Test_zh-CN_LangEnvSet`](https://github.com/maboloshi/github-chinese/tree/Test_zh-CN_LangEnvSet) 分支下的 [`main.user.js`](https://github.com/maboloshi/github-chinese/raw/Test_zh-CN_LangEnvSet/main.user.js) 进行体验

**Comment by wuyuncheng-26** [comment]
进一步讨论去 #146

**Comment by wuyuncheng-26** [comment]
@C-racker 您可以体验一下

**Comment by maboloshi** [comment]
目前, 仅支持浏览器默认大陆简中的时间格式, 不打算自定义格式(否则,又是基于原有模式, 性能有差别)
