### ISSUE TITLE
工作流时间翻译错误

### ISSUE THREAD

**Issue by bobandbrony** [maboloshi/github-chinese#141]
如图
![image](https://github.com/maboloshi/github-chinese/assets/129247570/558dc585-e8f0-4bad-87ad-8b6f4e0c2497)
而实际时间是16分钟59秒前

**Comment by maboloshi** [comment]
属于老问题了🤣 https://github.com/maboloshi/github-chinese/issues/10#issuecomment-1406207851

**Comment by maboloshi** [comment]
后期，等我有空给特定页面使用特殊正则规则

**Comment by wuyuncheng-26** [comment]
与 #10 重复

**Comment by wuyuncheng-26** [comment]
已找到此问题的解决方案
不过目前此功能尚未合并到主分支
可以去 [`Test_zh-CN_LangEnvSet`](https://github.com/maboloshi/github-chinese/tree/Test_zh-CN_LangEnvSet) 分支下的 [`main.user.js`](https://github.com/maboloshi/github-chinese/raw/Test_zh-CN_LangEnvSet/main.user.js) 进行体验
