### ISSUE TITLE
在使用github编辑代码的时候翻译器会自动把 . 翻译为 。导致被编辑的代码出现错误

### ISSUE THREAD

**Issue by szzz666** [maboloshi/github-chinese#142]
在使用github编辑代码的时候翻译器会自动把 . 翻译为 。导致被编辑的代码出现错误
建议不要翻译标点的符号

**Comment by maboloshi** [comment]
事实上，使用 GitHub 编辑代码建议关闭脚本，因为不仅仅`.`会被替换，还有其他不可知的词条被替换。
另外，还可以使用代码空间的编辑器

**Comment by wuyuncheng-26** [comment]
最近那么多 issues？？？

**Comment by maboloshi** [comment]
也说明使用的新朋友在增加
有必要对目前的bug写个说明 放到 [README](https://github.com/maboloshi/github-chinese#)
你方便执笔么@wuyuncheng-26

**Comment by wuyuncheng-26** [comment]
也许可以开个 issues 然后置顶？
可能放在 readme 靠下部分不会有人去翻

**Comment by maboloshi** [comment]
> 也许可以开个 issues 然后置顶？ 可能放在 readme 靠下部分不会有人去翻

也是一个不错的方式😊

**Comment by maboloshi** [comment]
测试版中基本修复
