### ISSUE TITLE
在使用github编辑代码的时候翻译器会自动把 .翻译为 。

### ISSUE THREAD

**Issue by szzz666** [maboloshi/github-chinese#143]
在使用github编辑代码的时候翻译器会自动把 .翻译为 。导致被编辑的代码出现错误
建议不要翻译标点的符号

**Comment by wuyuncheng-26** [comment]
@maboloshi

**Comment by wuyuncheng-26** [comment]
我觉得应该没有单独存在的句号吧 qwq
可能都是随着句子的

**Comment by maboloshi** [comment]
有单独的句号

**Comment by szzz666** [comment]
> 我觉得应该没有单独存在的句号吧 qwq 可能都是随着句子的

有单独的句号，不是随者句子

**Comment by szzz666** [comment]
https://github.com/maboloshi/github-chinese/assets/60167194/eace4251-ccc1-43b0-a5ec-e67b475cab4f

**Comment by wuyuncheng-26** [comment]
这种情况可能只能做区域限制

**Comment by wuyuncheng-26** [comment]
我把 #105 重新打开了，去那里讨论

**Comment by maboloshi** [comment]
测试版中基本修复
