### ISSUE TITLE
创建或评论议题前必看

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#144]
* 请不要发已存在的议题，目前一些常见 BUG：
  * 编辑代码时，代码中的 ` . ` 被替换为  `。`（#105）
  * GitHub Actions 时间翻译问题（#10）
  * 文件编辑时会误转换（#89）
* 不要发无用议题
* 如遇到暂未翻译的地方，可以提交议题，有能力的还可以提交拉取请求
* 不要有过激情绪
* 不要发表离题评论

**Comment by maboloshi** [comment]
后期，我默认删除`characterData`参数好了, 上面的第一和第三问题应该能解决

**Comment by wuyuncheng-26** [comment]
嗯？
