### ISSUE TITLE
HelloGitHub 徽章计划

### ISSUE THREAD

**Issue by 521xueweihan** [maboloshi/github-chinese#154]
您好，HelloGitHub 网站上的开源项目认领功能上线了，你那边是否有时间做一下[「开源项目认领」](https://hellogithub.com/repository/738d0abae49543f18d887a7e29ec9e90/embed)，认领后将获得一下权限：

- 社区认可： 徽章代表你的项目已通过 HelloGitHub 社区的严格筛选，并获得推荐。
- 增加曝光：完成认领（佩戴徽章）将获得更多推荐流量，吸引潜在用户和贡献者的目光。
- 互动机会：用户可通过徽章快速了解项目，并通过点赞、评论、收藏，增强社区互动。
- 反馈积累：收集来自广大用户的真实反馈，持续优化你的项目。
- 作者标识：认证后发布评论将显示醒目的标识，并获得评论置顶。

因为，项目佩戴徽章状态会绑定到 HelloGitHub 社区的账号，所以需要嵌入最新的「徽章代码」。

**Comment by wuyuncheng-26** [comment]
@maboloshi

**Comment by wuyuncheng-26** [comment]
认证权限：仅限于项目作者或拥有修改权限的成员。请确保您有足够的权限进行认领。
认证失败：仅限社区已收录的项目。如果您的项目尚未被收录，请先提交您的项目。
每个项目只能认领一次：认证后项目的认领者不可修改。请在操作前仔细检查所有信息。
需要帮助：可通过微信联系我：xueweihan（备注：认领）。

**Comment by 521xueweihan** [comment]
@wuyuncheng-26 我记得你的 ID，感谢分享如此优秀的项目。

**Comment by wuyuncheng-26** [comment]
可以反馈一个 BUG 吗，更新头像后 HelloGitHub 并不会更新

**Comment by 521xueweihan** [comment]
@wuyuncheng-26 这个只会在第一次登录后同步，我可以手动帮你更新！

**Comment by wuyuncheng-26** [comment]
好的谢谢

**Comment by 521xueweihan** [comment]
> 好的谢谢

@wuyuncheng-26 done. https://hellogithub.com/repository/738d0abae49543f18d887a7e29ec9e90

**Comment by wuyuncheng-26** [comment]
我去认领一下项目吧（

**Comment by wuyuncheng-26** [comment]
@521xueweihan 
#156 应该是可以了
不过我的头像好像还没更新（

**Comment by 521xueweihan** [comment]
@wuyuncheng-26 感谢！认证状态已确认，另外头像问题应该是浏览器缓存，可以尝试无痕模式访问：https://hellogithub.com/user/zepvSg6Vwl4EqMr

<img width="710" alt="image" src="https://github.com/maboloshi/github-chinese/assets/8255800/ae23b6df-3422-4990-b8d9-3b976a10bf5d">


<img width="702" alt="image" src="https://github.com/maboloshi/github-chinese/assets/8255800/13df6892-dae7-4085-84b0-6f59f4b30260">

**Comment by wuyuncheng-26** [comment]
好的

**Comment by wuyuncheng-26** [comment]
@521xueweihan 请问认证完后那部分代码是不能改了吗
之前改了，结果发现好像失效了😂

**Comment by wuyuncheng-26** [comment]
我已经递交申请了

**Comment by 521xueweihan** [comment]
@maboloshi  @wuyuncheng-26 那段代码尽量不要改，否则后续的定时检查容易出现异常。
我检查了你们的修改，符合要求已经重新通过认证了。

<img width="575" alt="image" src="https://github.com/maboloshi/github-chinese/assets/8255800/2e7518fd-42ee-4c0b-81dd-fbae1d753c53">

**Comment by wuyuncheng-26** [comment]
ok 知道了 谢谢
