### ISSUE TITLE
几处翻译遗漏

### ISSUE THREAD

**Issue by mpamxl** [maboloshi/github-chinese#157]
![Screenshot_20240607-112520_Via](https://github.com/maboloshi/github-chinese/assets/5687454/b8a9f407-54f3-4d7e-a360-5cbd6ffe0c9f)
![Screenshot_20240607-112546_Via](https://github.com/maboloshi/github-chinese/assets/5687454/5bde919e-777a-44e0-b40a-b0924988f173)

**Comment by TC999** [comment]
已提交拉取请求，等审核过了就修了

详见 #158

**Comment by mpamxl** [comment]
> 已提交拉取请求，等审核过了就修了
> 
> 详见 #158 

最新6月9日的脚本我图中位置依旧没有翻译

**Comment by wuyuncheng-26** [comment]
> > 已提交拉取请求，等审核过了就修了
> > 详见 #158
> 
> 最新6月9日的脚本我图中位置依旧没有翻译

试一下把脚本删除后重新安装，主版本号不更新，脚本管理器就不会跟着更新的
