### ISSUE TITLE
ToDo：增加 `www.githubstatus.com` 的翻译

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#161]
@maboloshi 大佬可以帮忙看一下 [`translate-status-page`](https://github.com/maboloshi/github-chinese/tree/translate-status-page) 分支吗
已经写成屎山代码了（bushi）
![00C2B2A6](https://github.com/maboloshi/github-chinese/assets/122529705/a71d08c0-a740-4bec-9cdf-ca5171026d86)

**Comment by wuyuncheng-26** [comment]
现在甚至其他网页都翻译不了了

**Comment by maboloshi** [comment]
1. 别动`main(greasyfork).user.js`文件, 这个是从充分测试过的`main.user.js`合并过去
2. 之前的`[zh-CN_LangEnvTest](https://github.com/maboloshi/github-chinese/tree/zh-CN_LangEnvTest)`分支合并太早了
3. 这个`dev`分支暂时也别合并

**Comment by wuyuncheng-26** [comment]
我发现出问题了，所以才不合并
合并太早又是什么意思

**Comment by maboloshi** [comment]
> 我发现出问题了，所以才不合并 合并太早又是什么意思

有 bug ,到时会影响很多人的用户体验

**Comment by wuyuncheng-26** [comment]
的确是这样的（

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/122529705/8f0e278a-f12d-462d-9685-dd28c5ddcbcb)
现在就算是主分支也会翻译失败了
很严重的问题

**Comment by TC999** [comment]
- 有概率翻译失败，要刷新几次
- 但Github安全页面、仓库依赖关系图页面直接没翻译，尽管有代码和页面正则匹配

**Comment by wuyuncheng-26** [comment]
别提了，这玩意装上后别的界面全部翻译不了

**Comment by TC999** [comment]
现在更离谱的来了

同一个页面刷新后每次翻译的东西都不一样

**Comment by maboloshi** [comment]
> 别提了，这玩意装上后别的界面全部翻译不了

你第2个提交引入了语法错误. 我知道你打算简化`www.githubstatus.com`的翻译, 调整不少主结构, 其实目前对性能提升意义不大.

**Comment by wuyuncheng-26** [comment]
？其实是每次控制台报错
我就写一个判断把这个网站排除掉

**Comment by maboloshi** [comment]
> ![image](https://private-user-images.githubusercontent.com/122529705/337698523-8f0e278a-f12d-462d-9685-dd28c5ddcbcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzUyNDEsIm5iZiI6MTcxNzc3NDk0MSwicGF0aCI6Ii8xMjI1Mjk3MDUvMzM3Njk4NTIzLThmMGUyNzhhLWYxMmQtNDYyZC05Njg1LWRkMjhjNWRkY2JjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTQyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWQ4MDkwZmRkNmQ5ZjU0NjYxZjEwZmQ3MWYyZTE3MTllMDc4NjEyODhiYzVhNmYyZDk2ZDU2YmRjYzE1NDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2jkO9drkVFojJP44XrbcvcD87D2XNuqBFuU89sdwX-U) 现在就算是主分支也会翻译失败了 很严重的问题

这个bug 可能是我调整时间元素翻译导致的 之前测试不充分

**Comment by maboloshi** [comment]
translate-status-page](https://github.com/maboloshi/github-chinese/tree/translate-status-page) 除了发现一处语法错误, 其他 bug 不排除是主分支引入的.

**Comment by wuyuncheng-26** [comment]
> [translate-status-page](https://github.com/maboloshi/github-chinese/tree/translate-status-page) 除了发现一处语法错误, 其他 bug 不排除是主分支引入的.

无法正常翻译似乎是 `document-start` 的副作用
要不还是暂时 revert 吧

**Comment by wuyuncheng-26** [comment]
不应该那么早合并 #158 的（

**Comment by maboloshi** [comment]
已更新主分支, 请测试 [8cfcfb6](https://github.com/maboloshi/github-chinese/commit/8cfcfb69ed2628811b412940029776ed5fa5c0b4)
