### ISSUE TITLE
左上的仓库名字应为也被翻译了，这块儿应该保持吧

### ISSUE THREAD

**Issue by DukeAnn** [maboloshi/github-chinese#17]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/15902491/231927381-1ae967ed-c932-4532-823d-b7a0fc60c74f.png">

**Comment by maboloshi** [comment]
Fix [562b7df](https://github.com/maboloshi/github-chinese/commit/562b7df30dfc5d58e0fa27877f2bd2cbabb4ea22)
