### ISSUE TITLE
Codespace(代码空间)页面翻译失效

### ISSUE THREAD

**Issue by Ohcecho** [maboloshi/github-chinese#20]
点击进入Codespace（代码空间）页面翻译失效，望修复，另外感谢作者如此积极地对这个脚本的维护，这对新手来说帮助很大

**Comment by Ohcecho** [comment]
另外点击进入explore-collections、explore-event、explore-GitHub sponsors这三个页面翻译也是失效的

**Comment by wuyuncheng-26** [comment]
忘记改状态了（

**Comment by wuyuncheng-26** [comment]
详情见 #27 与 #56

**Comment by wuyuncheng-26** [comment]
详情见 #27 与 #56

**Comment by wuyuncheng-26** [comment]
详情见 #27 与 #56
