### ISSUE TITLE
[Bug] Github Action 时间翻译错误

### ISSUE THREAD

**Issue by samzong** [maboloshi/github-chinese#207]
![image](https://github.com/maboloshi/github-chinese/assets/13782141/43a74e0e-18af-478d-b390-97c6dd55cded)

**Comment by maboloshi** [comment]
此问题已在测试版中修复，未来会合并到主分支中，请耐心等待

**Comment by wuyuncheng-26** [comment]
在发议题前，请务必查看 #144，以免造成议题重复

**Comment by wuyuncheng-26** [comment]
本议题与 #10 重复
