### ISSUE TITLE
关于git

### ISSUE THREAD

**Issue by buiawpkgew1** [maboloshi/github-chinese#208]
如果git clone Gitee上了怎么关联github？

**Comment by buiawpkgew1** [comment]
`SSL certificate problem: unable to get local issuer certificate`怎么解决

**Comment by maboloshi** [comment]
> 如果git clone Gitee上了怎么关联github？

来自AI kimi 的回复

> 
> Gitee和GitHub的关联可以通过几种方式实现，包括仓库镜像管理、手动同步更新等。以下是一些具体的方法：
> 
> 仓库镜像管理：Gitee提供了仓库镜像管理功能，可以实现Gitee和GitHub仓库之间的自动同步。配置仓库镜像后，当代码提交到Gitee时，Gitee会自动向GitHub同步仓库，反之亦然。这包括分支、标签和提交记录的同步。
> 
> 手动同步更新：如果仓库分支较少，可以在本地仓库通过命令行添加Gitee和GitHub的远程库，并使用git pull和git push命令在两个平台之间手动同步代码。对于分支较多的仓库，可以先克隆GitHub仓库到本地，然后一次性拉取所有分支，并推送到Gitee。
> 
> 使用Gitee的导入功能：Gitee允许用户直接从GitHub导入仓库。登录Gitee账号后，可以选择从GitHub导入仓库，这需要授权Gitee访问GitHub。
> 
> 在Gitee仓库主页使用同步更新按钮：对于分支较多的仓库，可以在Gitee仓库主页点击同步更新按钮，这将强制同步GitHub上的更新到Gitee，新代码将直接覆盖现有代码。
> 
> 请注意，镜像操作会覆盖目标仓库的分支、标签和提交记录，因此在操作前应确保已做好备份。同时，镜像触发的最短间隔时间为5分钟，且不支持同步Git-LFS，如果同步时间超过30分钟则视为超时。

**Comment by maboloshi** [comment]
> `SSL certificate problem: unable to get local issuer certificate`怎么解决

链接`github`的提示?, 一般网络的问题

**Comment by buiawpkgew1** [comment]
> > `SSL certificate problem: unable to get local issuer certificate`怎么解决
> 
> 链接`github`的提示?, 一般网络的问题

用的是steam++ 机翻是证书问题

**Comment by buiawpkgew1** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/71136405/9d16c858-cc3f-49e4-93f9-6a7573bda675)
