### ISSUE TITLE
Andorid中的And被翻译为和

### ISSUE THREAD

**Issue by gbostock** [maboloshi/github-chinese#215]
如图
![屏幕截图 2024-07-02 230355](https://github.com/maboloshi/github-chinese/assets/94212663/cf595b4f-fac8-430c-9c56-2a06c04ae74b)

**Comment by wuyuncheng-26** [comment]
老 bug了

**Comment by wuyuncheng-26** [comment]
误翻译罢了

**Comment by maboloshi** [comment]
不清楚`reIgnoreClass`规则中添加 `Truncate-text` 能否修复

**Comment by TC999** [comment]
临时修复 #216

**Comment by maboloshi** [comment]
明天提供个测试链接 @250h

**Comment by TC999** [comment]
测试链接是这个
<https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.2>

**Comment by maboloshi** [comment]
> 不清楚`reIgnoreClass`规则中添加 `Truncate-text` 能否修复

测试通过

**Comment by maboloshi** [comment]
Fix 0ba80181ccbe7fb41f1e94044f22caa0d3588759

**Comment by TC999** [comment]
出 BUG 了 #217

**Comment by maboloshi** [comment]
Fix 13e10196da1b833c99762372bcacc64f08757561
