### ISSUE TITLE
修复 #215 时，把其他页面需要翻译的元素也忽略了

### ISSUE THREAD

**Issue by TC999** [maboloshi/github-chinese#217]
## 如图所示（仪表板页面）

![image](https://github.com/maboloshi/github-chinese/assets/88823709/cb324bbc-5375-40e9-87fc-6a8808573867)

元素名称为`Truncate-text`
## 解决方案：
为发行版页面单独启用另外一套`reIgnoreClass`规则？或使用词条占用？

**Comment by maboloshi** [comment]
收到 我到时再看看

**Comment by maboloshi** [comment]
可能尝试使用 测试版中的`ignoreSelector`规则：`'repository/releases': [".Box-footer"],` ，貌似可行

**Comment by TC999** [comment]
可以，加上后没有问题

**Comment by maboloshi** [comment]
Fix 13e10196da1b833c99762372bcacc64f08757561
