### ISSUE TITLE
`*Ignore*`规则后续是否有必要分全局和局部？

### ISSUE THREAD

**Issue by maboloshi** [maboloshi/github-chinese#226]
如题

**Comment by TC999** [comment]
开个新分支测试先

**Comment by maboloshi** [comment]
有新想法了 规则合并为`selector`，使用`const skipNode = node => selectorPage[page]?.some(selector => node.matches(selector));`进行判断

目前是每个`page`的细分规则，规则有点复杂，还得考虑公共规则和规则应用
