### ISSUE TITLE
组织存档黄色横幅

### ISSUE THREAD

**Issue by qznfbnj** [maboloshi/github-chinese#227]
[/This organization was marked as archived by an administrator on (.+)\. It is no longer maintained\./, "此组织已于 $1 被管理员标记为已存档。它将不再被维护。"],
所有选项卡都有
![image](https://github.com/maboloshi/github-chinese/assets/100760086/4859908a-b413-47ca-8bef-cdb8e6c1b23a)
还有仪表板
![image](https://github.com/maboloshi/github-chinese/assets/100760086/5e25a20d-901a-4d8e-98d7-3c0b1dec2f01)
要整一个 I18N.zh["orgs-public"]么？还是复制粘贴 6次（选项卡）+ 30+次（设置） = 36+次（

**Comment by TC999** [comment]
试下放这里
I18N.zh["pubilc"]

**Comment by maboloshi** [comment]
> I18N.zh["orgs-public"]

我之前就有计划整`I18N.zh["orgs-public"]` 没放上来而已

另外，顺便把这个也帮我整上吧。
![image](https://github.com/maboloshi/github-chinese/assets/7850715/f9511483-748f-4ec5-88ba-d82d681a36ae)

**Comment by qznfbnj** [comment]
> 试下放这里 I18N.zh["pubilc"]

你猜我为什么不提这个（
因为没用

**Comment by TC999** [comment]
> > 试下放这里 I18N.zh["pubilc"]
> 
> 你猜我为什么不提这个（ 因为没用

……

**Comment by maboloshi** [comment]
> orgs-public

本来就在 只是没启用哈哈
https://github.com/maboloshi/github-chinese/blob/a91cfdd647d032267c707b4dcbdae70f32287fd9/locals.js#L2303-L2312

**Comment by qznfbnj** [comment]
> > orgs-public
> 
> 本来就在 只是没启用哈哈 https://github.com/maboloshi/github-chinese/blob/a91cfdd647d032267c707b4dcbdae70f32287fd9/locals.js#L2303-L2312

草
那可太好了，正懒得复制粘贴 36 次（

**Comment by maboloshi** [comment]
fix 2fff56a550006150f980827072efafbd77ec45da
