### ISSUE TITLE
评论被错误的翻译

### ISSUE THREAD

**Issue by CN-traveler** [maboloshi/github-chinese#23]
# 评论被错误的翻译

## 复现

```markdown
[pull requests](https://github.com/microsoft/winget-pkgs/pulls)
```

[pull requests](https://github.com/microsoft/winget-pkgs/pulls)

> 在[编辑评论 -> 预览]可复现，页面中有几率复现具体原因不详。

## 建议

可否添加黑名单，对评论区、源码等不需要翻译的地方进行过滤。

**Comment by maboloshi** [comment]
Fix cbf48cc
