### ISSUE TITLE
Chrome 切换到 Manifest V3后，使用问题

### ISSUE THREAD

**Issue by vercen** [maboloshi/github-chinese#234]
使用的是谷歌浏览器，安装最新的脚本，没有汉化成功。打开新标签页也不行
![image](https://github.com/maboloshi/github-chinese/assets/70558042/951fbd65-b13b-4956-adc2-ce8675cdb3ce)
![image](https://github.com/maboloshi/github-chinese/assets/70558042/2c2a92b1-f2a9-4980-b9de-9e52fab99801)
![image](https://github.com/maboloshi/github-chinese/assets/70558042/f7827d03-d4c6-4286-ae3b-7d90880396f2)

**Comment by TC999** [comment]
注意"**已启用**"上方的英文，提示需要打开开发者模式

**Comment by maboloshi** [comment]
尝试一下：https://www.tampermonkey.net/faq.php?locale=zh#Q209

**Comment by maboloshi** [comment]
由于 Chrome 127 及以上官方分阶段停用了 Manifest V2 扩展程序，对于基于`Manifest V2`相关脚本管理器会自动被停用

> 最早会在 2024 年 6 月的 Chrome 127 及更高版本中停用[稳定版 Chrome](https://developer.chrome.com/docs/web-platform/chrome-release-channels?hl=zh-cn)（开发者版、Canary 版和 Beta 版）中的 Manifest V2 扩展程序。受分阶段发布影响的用户将在浏览器中看到自动停用 Manifest V2 扩展程序，并且无法再通过 Chrome 应用商店安装 Manifest V2 扩展程序。2024 年 6 月的 Chrome 127 及更高版本中停用[稳定版 Chrome](https://developer.chrome.com/docs/web-platform/chrome-release-channels?hl=zh-cn)（开发者版、Canary 版和 Beta 版）中的 Manifest V2 扩展程序。受分阶段发布影响的用户将在浏览器中看到自动停用 Manifest V2 扩展程序，并且无法再通过 Chrome 应用商店安装 Manifest V2 扩展程序。—— [恢复向 Manifest V3 的转换](https://developer.chrome.com/blog/resuming-the-transition-to-mv3?hl=zh-cn#the_phase-out_timeline)

对于 Chrome 127 及以上，安装 Tampermonkey 5.2.0 及以上必须在浏览器的`扩展程序管理`中开启`开发者模式`，才能通过 Tampermonkey 运行用户脚本。

**Comment by maboloshi** [comment]
目前，Chrome 陆续开始强行切换到 Manifest V3，不太清楚相关脚本管理器支持的怎样的程度。大家拭目以待吧，N 多常用的浏览器扩展会挂掉。

PS：[violentmonkey](https://github.com/violentmonkey/violentmonkey)目前不支持 Manifest V3。

**Comment by TC999** [comment]
讨论区提到的"脚本猫"也是V2

**Comment by wuyuncheng-26** [comment]
@vercen 请开启设置里的开发者模式，不会可以去看看网上教程
这个不是脚本的问题

**Comment by wuyuncheng-26** [comment]
参见 https://www.tampermonkey.net/faq.php?locale=zh#Q209
```
如何启用开发者模式
在 Chrome 及其衍生浏览器中启用开发者模式的步骤：

打开菜单，选择“扩展程序”和“管理扩展程序”，或在新的浏览器标签页中输入 chrome://extensions 或 edge://extensions 来导航到扩展页面。

在页面右上角找到并点击“开发者模式”开关以启用它。
```

**Comment by maboloshi** [comment]
关于 暴力猴 / violentmonkey 见这里 https://github.com/violentmonkey/violentmonkey/issues/2284
