### ISSUE TITLE
翻译位置错误

### ISSUE THREAD

**Issue by nsnans** [maboloshi/github-chinese#236]
## 错误
![image](https://github.com/maboloshi/github-chinese/assets/68949154/7f29c766-e914-427d-a4c8-5153b8b730de)

![image](https://github.com/maboloshi/github-chinese/assets/68949154/561a2534-7624-4417-8629-1b30d6e244dd)

![image](https://github.com/maboloshi/github-chinese/assets/68949154/eb1add1a-4e8c-4372-8c34-e3f54d3584f5)

![image](https://github.com/maboloshi/github-chinese/assets/68949154/0b08b096-edd5-445c-b4fc-ba3f9ba4332f)

## 原版

![image](https://github.com/maboloshi/github-chinese/assets/68949154/77b84d5f-45a5-49c5-bfe8-1a67f477a0ba)

**Comment by wuyuncheng-26** [comment]
老问题了

**Comment by nsnans** [comment]
> 老问题了

翻译dom那里，根据class或者attr分辨出是这几个区域，排除掉应该就可以吧

**Comment by wuyuncheng-26** [comment]
特征性不大

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/122529705/9354e6a4-46f7-42dc-98e8-e0e390e07901)
正如这种情况 非常郁闷

**Comment by maboloshi** [comment]
Fix #248
