### ISSUE TITLE
部分含有and的被翻译成和

### ISSUE THREAD

**Issue by charley008** [maboloshi/github-chinese#238]
如图：
![屏幕截图 2024-07-10 222019](https://github.com/maboloshi/github-chinese/assets/24822683/d2e30c70-bd60-41ce-972a-a23d7bf54172)

**Comment by TC999** [comment]
词条可能在仓库 - 公共部分下的正则翻译里
把这个词条删除或注释掉就行
```
[/and/, "和"],
```

**Comment by charley008** [comment]
> 词条可能在仓库 - 公共部分下的正则翻译里 把这个词条删除或注释掉就行
> 
> ```
> [/and/, "和"],
> ```

按此方法的确解决了，话说 这个and 真没必要翻译了吧？

**Comment by wuyuncheng-26** [comment]
与 #215 和 #236 重复

**Comment by maboloshi** [comment]
> 词条可能在仓库 - 公共部分下的正则翻译里 把这个词条删除或注释掉就行
> 
> ```
> [/and/, "和"],
> ```

这个正则写的不太好 误杀太大，建议后期进行调整

**Comment by charley008** [comment]
> 这个正则写的不太好 误杀太大，建议后期进行调整

我是觉得这个and 没必要翻译了，就像“bye“ 没必要翻译成 “再见“ 类似。

**Comment by charley008** [comment]
[/ and /, "和"] 加个空格呢？这样会不会好一点

**Comment by maboloshi** [comment]
```
commit 67027fa4835daea1b79bb59944aa90476ced2dfd
Author: 陈生杂物房 <88823709+TC999@users.noreply.github.com>
Date:   Tue Jul 2 16:01:55 2024 +0800

    增删词条：搜索页、比较页、仓库页、拉取请求页、复刻页 (#209)

commit b7c000ba8ebaa7763f768b01aa8aea7300016e06
Author: 陈生杂物房 <88823709+TC999@users.noreply.github.com>
Date:   Sat Jun 29 21:12:37 2024 +0800

    增加词条：零散词条补充 (#197)
```
@TC999 请回忆一下当初引入这2条规则，是要解决什么场景或词条翻译？

**Comment by TC999** [comment]
好像是"提交检查"和发行版页面"贡献者"

**Comment by TC999** [comment]
> [/ and /, "和"] 加个空格呢？这样会不会好一点

前后有空格脚本不会匹配

**Comment by TC999** [comment]
看后期把这个词条改成其他东西

**Comment by TC999** [comment]
等下，刚才测试时前后加空格就解决了

**Comment by maboloshi** [comment]
> [/ and /, "和"] 加个空格呢？这样会不会好一点

杀伤力依然较大，只是稍微好一点
