### ISSUE TITLE
右侧搜索结果下的.被翻译为句号

### ISSUE THREAD

**Issue by yizhuying** [maboloshi/github-chinese#240]
GitHub仓库地址：https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/api/v1/system/sys_auto_code_history.go

<img width="1547" alt="Google Chrome 2024-07-12 09 41 23" src="https://github.com/user-attachments/assets/a3af02a6-a962-4ee8-b9c9-be26a9077a5d">

**Comment by maboloshi** [comment]
问题已找到，估计对`id`的过滤还是得使用正则方式 🤣

**Comment by yizhuying** [comment]
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/59f86eda-0893-4412-90d5-2149f404e7d1">
还有一个问题，这里显示的是删除，实际函数是Delete
GitHub地址：
https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/api/v1/system/sys_auto_code_history.go

**Comment by maboloshi** [comment]
>  还有一个问题，这里显示的是删除，实际函数是Delete GitHub地址： https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/api/v1/system/sys_auto_code_history.go

这个问题我也已识别到 😊 后期会修正

**Comment by yizhuying** [comment]
👍🏻👍🏻👍🏻

**Comment by maboloshi** [comment]
Fix a2ba35bac0a698ea5e9b0072a4600c6049b63327
