### ISSUE TITLE
请问装的开发版没反应，装发布版一切正常？

### ISSUE THREAD

**Issue by itheabyss** [maboloshi/github-chinese#241]
还有就是readme说开发版比发布版更快，可我装完发布版想换成开发版时，发现还要降级。而且版本号也比发布版低是为啥？谢谢

**Comment by itheabyss** [comment]
比如就是现在，发布版是20240712，而开发版是20240708。关键是发布版装上还根本没反应

**Comment by maboloshi** [comment]
自从自动更新被人为打断之后, 有点乱了 我到时人为调整一下🤔

**Comment by maboloshi** [comment]
看似版本号`发布版20240712` 大于 `开发版20240712`, 内容确实相差一周的时间.
版本号设置有 Bug, 🤔 后期考虑修复方案

**Comment by maboloshi** [comment]
> 比如就是现在，发布版是20240712，而开发版是20240708。关键是发布版装上还根本没反应

降级安装没反应?

**Comment by maboloshi** [comment]
发布版实测可以使用, 请尝试删除后重新安装一下

**Comment by itheabyss** [comment]
不好意思，是我打错了。是开发版不能用，因为发布版的日期更新，装上是可用的，然后点开发版，显示需要降级，降级后刷新，全部变成英文。

然后我删掉重新安装开发版，还是全英文，再升级成发布版，一切正常。

总之就是开发版不能，发布版一切正常。

**Comment by itheabyss** [comment]
> 发布版实测可以使用, 请尝试删除后重新安装一下

不好意思，是我打错了。说的是开发版不可用。

无论是从发布版降级安装开发版，还是全新安装开发版，都是英文，刷新页面完全没反应。

而安装发布版则一切正常。

**Comment by maboloshi** [comment]
> > 发布版实测可以使用, 请尝试删除后重新安装一下
> 
> 不好意思，是我打错了。说的是开发版不可用。
> 
> 无论是从发布版降级安装开发版，还是全新安装开发版，都是英文，刷新页面完全没反应。
> 
> 而安装发布版则一切正常。

不好意思，我今天修复#240 的时候，没修复完全 😢

另外，发行版的词库版本号逻辑已调整 a07c78d5e4a1f855c893e6552d237f8c29d7c806 感谢反馈 ❤️
