### ISSUE TITLE
时不时会把英文中的 .  替换为中文的句号。

### ISSUE THREAD

**Issue by sanbei101** [maboloshi/github-chinese#245]
![image](https://github.com/user-attachments/assets/790b0a55-6f15-4c89-a5a3-9d9799b4b7a6)
**这个现象有的时候会发生,很玄学,刷新有一定概率消除**

**Comment by maboloshi** [comment]
测试版中基本修复

**Comment by wuyuncheng-26** [comment]
发议题前请先检查有没有重复议题
与 #105 重复
