### ISSUE TITLE
在搜索框中输入download 会变成 次下载

### ISSUE THREAD

**Issue by ewwwda** [maboloshi/github-chinese#25]
试了几次发现触发条件。在搜索框中，输入数字+空格+download，就会变成“次下载”
![QQ截图20230716131449](https://github.com/maboloshi/github-chinese/assets/29039907/295e662b-2a6f-402e-b7ae-d765e9e953bb)
![QQ截图20230716131458](https://github.com/maboloshi/github-chinese/assets/29039907/d43661ce-6531-46f5-bb0a-784a9be87911)

**Comment by maboloshi** [comment]
我这未重现

**Comment by ewwwda** [comment]
> 

看了一下，确实。貌似只有在搜索界面内才会有。

**Comment by maboloshi** [comment]
嗯 问题复现。目前，新版搜索页面还没适配。

**Comment by maboloshi** [comment]
Fix 4833f25
