### ISSUE TITLE
当前版本在安装后再chrome浏览器中使用篡改猴条件下无法被执行

### ISSUE THREAD

**Issue by DDDDDduang** [maboloshi/github-chinese#250]

**Comment by TC999** [comment]
打开浏览器开发者模式，再不行就在词条文件地址前加上这个（详见README本地调试部分）：
```
https://mirror.ghproxy.com/
```

**Comment by maboloshi** [comment]
请提供浏览器版本号和篡改猴版本信息，我估计是 chrome MV3的问题。
详见 #234

**Comment by wuyuncheng-26** [comment]
请问有开启开发者模式吗？
详见 https://github.com/maboloshi/github-chinese/issues/234#issuecomment-2213480708

**Comment by TC999** [comment]
有时网络卡顿导致词库文件没有下载到本地，可以在词条文件地址前加上这个（详见README本地调试部分）：
```
https://mirror.ghproxy.com/
```

**Comment by DDDDDduang** [comment]
chorm版本 126.0.6478.183（正式版本） （64 位）
篡改猴：V5.2.3
________________________________
发件人: 沙漠之子 ***@***.***>
发送时间: 2024年7月25日 14:24
收件人: maboloshi/github-chinese ***@***.***>
抄送: DDDDDduang ***@***.***>; Author ***@***.***>
主题: Re: [maboloshi/github-chinese] 当前版本在安装后再chrome浏览器中使用篡改猴条件下无法被执行 (Issue #250)


请提供浏览器版本号和篡改猴版本信息，我估计是 chrome MV3的问题。
详见 #234<https://github.com/maboloshi/github-chinese/issues/234>

―

**Comment by wuyuncheng-26** [comment]
> chorm版本 126.0.6478.183（正式版本） （64 位）
> 篡改猴：V5.2.3

您试试按照教程开启开发者模式，不行的话应该就是网络问题了，参考 TC999 的评论

**Comment by DDDDDduang** [comment]
好的感谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 是小胖呀26 ***@***.***>
发送时间: Thursday, July 25, 2024 3:10:36 PM
收件人: maboloshi/github-chinese ***@***.***>
抄送: DDDDDduang ***@***.***>; Author ***@***.***>
主题: Re: [maboloshi/github-chinese] 当前版本在安装后再chrome浏览器中使用篡改猴条件下无法被执行 (Issue #250)


chorm版本 126.0.6478.183（正式版本） （64 位）
篡改猴：V5.2.3

您试试按照教程开启开发者模式，不行的话应该就是网络问题了，参考 TC999 的评论

―
