### ISSUE TITLE
在via(至少是我手机)上没有翻译

### ISSUE THREAD

**Issue by Karmisu** [maboloshi/github-chinese#251]
via版本为5.7.1，安卓版本为8.1，插件版本为1.9.2-2024-07-21
在刷新后并没有翻译(只启用了这个插件)，但1.9.2-2024-07-26版本的可以正常翻译

**Comment by maboloshi** [comment]
GreasyFork 托管【发布版】 已修复，删除重新安装即可

**Comment by maboloshi** [comment]
由于`require`中的版本号未更新导致，重新安装脚本，依然存在没有更新词库文件的情况，故需要先清除缓存，再重新安装。
后期，考虑更新是同步修改`require`添加词库版本
