### ISSUE TITLE
【BUG】面包屑翻译位置错误

### ISSUE THREAD

**Issue by kilvn** [maboloshi/github-chinese#252]
![image](https://github.com/user-attachments/assets/fb18ee7f-a6a5-462a-bff7-d1174f17273b)

这个好像不用翻译吧，就算要翻译也只是选择性翻译，看起来很奇怪🤔

**Comment by maboloshi** [comment]
开发版词库中已临时修复 25d6976c5bac73e4de56aa7cb049d36588088dc1，发布版词库，本周五自动更新
