### ISSUE TITLE
主页动态中的文本被意外替换

### ISSUE THREAD

**Issue by AnYiEE** [maboloshi/github-chinese#253]
如图所示：
![Screenshot](https://github.com/user-attachments/assets/35d8050a-262b-49b8-b317-20a8faf0d068)

正确的应该是按原样“from v20240131 **to** v20240731”。

**Comment by AnYiEE** [comment]
其他的：
![Screenshot](https://github.com/user-attachments/assets/f48377d5-6dae-41ae-a223-3c061261e21d)
![Screenshot](https://github.com/user-attachments/assets/c1d377e5-84be-484d-9fad-cd49224ef50a)

**Comment by TC999** [comment]
老BUG了，重复议题 #104

**Comment by maboloshi** [comment]
`reIgnoreClass`规则直接使用`markdown-body`即可修复 但是 会有 #221 问题
