### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by nsnans** [maboloshi/github-chinese#256]
测试链接：https://github.com/OweQian/cli-oweqian/tree/develop/packages
## 原文
![image](https://github.com/user-attachments/assets/1b23b7b5-43e2-4bff-a6e3-2e6822d26ff2)
## 开启脚本后
![image](https://github.com/user-attachments/assets/9bb1a3ce-2bb3-4629-b991-dbc8ac0606d0)

**Comment by maboloshi** [comment]
`class`规则`react-tree-show-tree-items` 后期更新修复

**Comment by wuyuncheng-26** [comment]
所在元素是 `PRIVATE_TreeView-item-content-tex`？

**Comment by maboloshi** [comment]
> 所在元素是 `PRIVATE_TreeView-item-content-tex`？
> 
> ![image](https://private-user-images.githubusercontent.com/122529705/358911048-1ad064c9-ac7f-426c-bbca-3cc4f022ab1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODk3NzgsIm5iZiI6MTcyMzk4OTQ3OCwicGF0aCI6Ii8xMjI1Mjk3MDUvMzU4OTExMDQ4LTFhZDA2NGM5LWFjN2YtNDI2Yy1iYmNhLTNjYzRmMDIyYWIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxMzU3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzFlOWMwMjVkYzhiMDk0OTMxNmRjOGJiYzhmMDhiOWU0OWRkMjRmOTAyYThlZGI2ZTUwZGE0MzVjODIwZDZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xoard9FAUVKmYvJy10J1PYI9dAfi9TES2wkd7KlCZ9I)

本以为直接使用`.react-tree-show-tree-items`能解决 实际无效😒

**Comment by maboloshi** [comment]
`.PRIVATE_TreeView-item-content-text`也无效😪

**Comment by wuyuncheng-26** [comment]
难绷，先咕着吧
<img src="https://img-static.mihoyo.com/communityweb/upload/8568e2f26acbd1b86ae03dbf4b62f1b7.png" alt="米游姬咕咕" width="75" >

**Comment by maboloshi** [comment]
有效的, 用错测试文件了
![0A9EB292](https://github.com/user-attachments/assets/7a7a8507-0c5a-4cb9-9879-6dc34a1a5d49)

**Comment by maboloshi** [comment]
```
            'div.react-tree-show-tree-items', // 左侧文件树项目
            'tbody > tr', // 文件列表
```
