### ISSUE TITLE
可以在READMI.md的“浏览器与脚本管理器”一节中将“油猴”这个翻译附上吗

### ISSUE THREAD

**Issue by Kide-Lee** [maboloshi/github-chinese#26]
我第一次安装这个插件时一时意识不到所谓的“脚本管理器”是什么东西，所以在安装时下意识忽略了“请先安装用户脚本管理器”。等下载了一个js文件，又各种折腾，然后才意识到或许可以用油猴脚本试一试。

结果安装好油猴后可以自动安装插件了。

等我又折回来研究README.md时，发现里面有个叫[Tampermonkey](http://tampermonkey.net/)的东西似乎就是我刚刚下载的油猴插件。说真的我对“Tampermonkey”这十二个单词真不如“油猴”这两个字更敏感，兴许是我的问题吧。

**Comment by Kide-Lee** [comment]
另外我不喜欢edge扩展中翻译的“篡改猴”，明明已经有约定俗成的翻译了还要硬翻译。

**Comment by maboloshi** [comment]
油猴对应的是[Greasemonkey](https://zh.wikipedia.org/zh-hans/Greasemonkey)
