### ISSUE TITLE
ToDo：新版仓库洞察贡献者界面需翻译

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#267]
![image](https://github.com/user-attachments/assets/d8bd4236-4f75-4a27-8193-53071a801154)
尚未翻译

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/ab868cb6-5187-4f3b-beb9-90e1fde3bc5e)

**Comment by TC999** [comment]
#269 全部加上了
