### ISSUE TITLE
这个页面应该还没翻译

### ISSUE THREAD

**Issue by sdhzwc** [maboloshi/github-chinese#28]
![image](https://github.com/maboloshi/github-chinese/assets/46134044/9fb66122-f6c1-4a2b-aa17-68278d796d47)

问个小问题
![image](https://github.com/maboloshi/github-chinese/assets/46134044/36fd8d02-f826-41db-aef4-e603207f3f62)
油猴加载顺序 您知道吗 我看您的脚本始终在最前面

**Comment by wuyuncheng-26** [comment]
翻译好了，只用等待PR合并了
![image](https://github.com/maboloshi/github-chinese/assets/122529705/1952da2e-9504-48d9-bf1a-0aa30a69a487)
不过又发现两个没翻译的
![image](https://github.com/maboloshi/github-chinese/assets/122529705/5e966aa9-bbf4-4358-99d8-9187f220a4e1)
![image](https://github.com/maboloshi/github-chinese/assets/122529705/7d03992a-e8aa-4b28-822e-dd13f40d92bc)

**Comment by sdhzwc** [comment]
> 翻译好了，只用等待PR合并了
> ![image](https://github.com/maboloshi/github-chinese/assets/122529705/1952da2e-9504-48d9-bf1a-0aa30a69a487)
> 不过又发现两个没翻译的
> ![image](https://github.com/maboloshi/github-chinese/assets/122529705/5e966aa9-bbf4-4358-99d8-9187f220a4e1)
> ![image](https://github.com/maboloshi/github-chinese/assets/122529705/7d03992a-e8aa-4b28-822e-dd13f40d92bc)

速度呀，兄弟
我现在用的两个结合体解决的😁

**Comment by wuyuncheng-26** [comment]
@sdhzwc 已经合并了
![image](https://github.com/maboloshi/github-chinese/assets/122529705/a5451887-184d-477a-99ca-f6c1b1145027)

**Comment by sdhzwc** [comment]
> > 还有这个作者提供的插件，不过没有本插件更全面 https://github.com/k1995/github-i18n-plugin
> 
> 之前有给`github-i18n-plugin`做贡献, 满足不了自己的需求就独立维护了

油猴需要更新一下 谢谢

**Comment by maboloshi** [comment]
已更新 @sdhzwc
