### ISSUE TITLE
BUG: Github Copilot 翻译有问题

### ISSUE THREAD

**Issue by doit132** [maboloshi/github-chinese#280]
进入个人设置页面, 发现下面情况
![image](https://github.com/user-attachments/assets/e6133222-5ad7-4b5b-8723-b5f89db07b14)

**Comment by TC999** [comment]
如何复现此问题，进去一切正常

**Comment by doit132** [comment]
> 如何复现此问题，进去一切正常

![image](https://github.com/user-attachments/assets/f25b239a-539d-41ab-a5b3-6caf51e27c17)

这个 插件引起的, 这个插件有一个设置, 将 github 加入了黑名单, 现在这个问题不会出现了
这个插件叫: 个人词库

**Comment by TC999** [comment]
> > 如何复现此问题，进去一切正常
> 
> ![image](https://private-user-images.githubusercontent.com/117004316/367723231-f25b239a-539d-41ab-a5b3-6caf51e27c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjczNDEsIm5iZiI6MTcyNjU2NzA0MSwicGF0aCI6Ii8xMTcwMDQzMTYvMzY3NzIzMjMxLWYyNWIyMzlhLTUzOWQtNDFhYi1hNWIzLTZjYWY1MWUyN2MxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwOTU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmY3NjZmNDViOTZhM2U2ZWI2Y2E3OTdhMDU4MzVkNWFhNDgwODdhNTNhMzgxZTQ0MWM5MTA5NDY4Njg1ZmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e5Ep08BXBaFJEjJs3AEaAJJybgijTaH5_OIzdZO5EI8)
> 
> 这个 插件引起的, 这个插件有一个设置, 将 github 加入了黑名单, 现在这个问题不会出现了 这个插件叫: 个人词库

发个链接来，我也看下

**Comment by doit132** [comment]
https://mingchang.wang/

**Comment by TC999** [comment]
试了下，应该是 GitHub 这个词没有对应的中文翻译，然后疯狂输出

可能是“个人词库”插件本身的BUG，去 gitee 反馈一下，这个BUG会导致网页卡死
<https://gitee.com/wamich/personal-vocabulary/issues>
建议把这个议题关了（

**Comment by wyc-26** [comment]
I will do that

**Comment by maboloshi** [comment]
@wyc-26 你的大号还没恢复？目前进度怎样

**Comment by wyc-26** [comment]
三周了，没有任何进展
不过能够正常的加 Tag 和关 Issue
