### ISSUE TITLE
讯飞翻译失效了

### ISSUE THREAD

**Issue by gigibooom** [maboloshi/github-chinese#282]
如题

**Comment by maboloshi** [comment]
实测问题未复现，能正常工作。请提供详细的复现测试信息

**Comment by wyc-26** [comment]
我这里成功复现

**Comment by gigibooom** [comment]
> 实测问题未复现，能正常工作。请提供详细的复现测试信息

![image](https://github.com/user-attachments/assets/8b6610f4-bc63-418a-a8b8-bd2feacdbe35)

**Comment by gigibooom** [comment]
> 实测问题未复现，能正常工作。请提供详细的复现测试信息

![image](https://github.com/user-attachments/assets/c255f854-1c22-4a31-9330-5ec26db73a83)

**Comment by maboloshi** [comment]
请提供一下以下信息：浏览器及浏览器版本号、脚本管理器及脚本管理器版本号、脚本的版本号

**Comment by gigibooom** [comment]
> 请提供一下以下信息：浏览器及浏览器版本号、脚本管理器及脚本管理器版本号、脚本的版本号

edge 129.0.2792.65
暴力猴 v2.25.0
版本 1.9.2-2024-08-11

**Comment by TC999** [comment]
确实失效了，篡改猴直接没有任何反应
chromium 124.0.6367.91
篡改猴测试版 v5.3.6204
版本 1.9.3-2024-08-18

**Comment by maboloshi** [comment]
> > 请提供一下以下信息：浏览器及浏览器版本号、脚本管理器及脚本管理器版本号、脚本的版本号
> 
> edge 129.0.2792.65 暴力猴 v2.25.0 版本 1.9.2-2024-08-11

我使用microsoftedge-beta: 129.0.2792.41
没发现问题😒

尝试使用最新版本的“篡改猴”并开启“开发者模式”看看

**Comment by gigibooom** [comment]
> > > 请提供一下以下信息：浏览器及浏览器版本号、脚本管理器及脚本管理器版本号、脚本的版本号
> > 
> > 
> > edge 129.0.2792.65 暴力猴 v2.25.0 版本 1.9.2-2024-08-11
> 
> 我使用microsoftedge-beta: 129.0.2792.41 没发现问题😒
> 
> 尝试使用最新版本的“篡改猴”并开启“开发者模式”看看

我使用microsoftedge-beta: 130.0.2849.5
也没问题

**Comment by maboloshi** [comment]
> 并开启“开发者模式”看看

开启“开发者模式”看看

**Comment by maboloshi** [comment]
> 确实失效了，篡改猴直接没有任何反应 chromium 124.0.6367.91 篡改猴测试版 v5.3.6204 版本 1.9.3-2024-08-18

开启“开发者模式”看看

**Comment by maboloshi** [comment]
> > 请提供一下以下信息：浏览器及浏览器版本号、脚本管理器及脚本管理器版本号、脚本的版本号
> 
> edge 129.0.2792.65 暴力猴 v2.25.0 版本 1.9.2-2024-08-11

已测试没发现问题

**Comment by gigibooom** [comment]
<img width="319" alt="image" src="https://github.com/user-attachments/assets/274fbe3b-0eeb-4c1c-9830-3310a96ebf79">
试试这个，我的问题已经解决了

**Comment by wyc-26** [comment]
那我就先关咯
