### ISSUE TITLE
增加copliot相关的翻译

### ISSUE THREAD

**Issue by LynnGuo666** [maboloshi/github-chinese#287]
RT，希望增加copliot 相关页面（如右下角的小窗、设置页面）的翻译。

**Comment by wyc-26** [comment]
指的是 https://github.com/copilot 吗
个人觉得这个界面太少用了，无需翻译
毕竟平常都是在 IDE 里面用 Copilot 的么（

**Comment by TC999** [comment]
我个人认为没啥必要，vsc里一堆免费的GPT（

**Comment by LynnGuo666** [comment]
> 指的是 https://github.com/copilot 吗 个人觉得这个界面太少用了，无需翻译 毕竟平常都是在 IDE 里面用 Copilot 的么（

我指的是右下角那个小窗口（），翻GH仓库时候还算常用，感觉可以翻译一下

**Comment by TC999** [comment]
没事，这个页面就2句话需要翻译，整完 #288

**Comment by TC999** [comment]
词条加得差不多了，这个议题可以关了罢（
