### ISSUE TITLE
新主页还没翻译

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#29]
最近 GitHub 更新了新的主页，好像还没翻译（最近开学了，没时间翻译了）
![image](https://github.com/maboloshi/github-chinese/assets/122529705/c0582fdf-273e-42a4-9495-94c9f9ef0b3b)

**Comment by maboloshi** [comment]
🤣哎 github 又更新了 最近没啥时间鸟它

**Comment by maboloshi** [comment]
有2个提交还没合并你怎么删了呀 恢复一下 我来合并

**Comment by wuyuncheng-26** [comment]
？？？

**Comment by wuyuncheng-26** [comment]
我一般 PR 合并后都会把 fork 的仓库给删了（毕竟没啥用了）

**Comment by wuyuncheng-26** [comment]
可能是我上次不小心弄到了

**Comment by wuyuncheng-26** [comment]
算了，我周末再找时间提个 PR 翻译一下😀😀😀
