### ISSUE TITLE
新增Zh-TW翻译

### ISSUE THREAD

**Issue by Falldielove** [maboloshi/github-chinese#295]
本人台湾用户，虽然不是介意简体字，但因为字体文档关系，希望可以新增**Zh-TW**模块。

**Comment by TC999** [comment]
有这个分支，名字就叫`zh-TW`

参照自述文件上的说明安装就行

**Comment by wyc-26** [comment]
已经有了呀，而且是最近才加的呢 ~

**Comment by maboloshi** [comment]
要是用专业的github-action就好了 可以自动翻译

**Comment by buiawpkgew1** [comment]
> 要是用专业的github-action就好了 可以自动翻译

你说的有不过要json文件

**Comment by maboloshi** [comment]
> > 要是用专业的github-action就好了 可以自动翻译
> 
> 你说的有不过要json文件

比如什么工具？

**Comment by buiawpkgew1** [comment]
> > > 要是用专业的github-action就好了 可以自动翻译
> > 
> > 
> > 你说的有不过要json文件
> 
> 比如什么工具？

https://zh.crowdin.com/

**Comment by maboloshi** [comment]
@Falldielove 已正式增加繁体版
