### ISSUE TITLE
没有issue search的翻译

### ISSUE THREAD

**Issue by k1958992420xgd** [maboloshi/github-chinese#303]

**Comment by TC999** [comment]
截张图上来，以及原链接

**Comment by TC999** [comment]
你说的是<https://github.com/issues>吗

**Comment by k1958992420xgd** [comment]
应该是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 晚上8:58
收件人: ***@***.***&gt;;
抄送: "zexiang ***@***.******@***.***&gt;;
主题: Re: [maboloshi/github-chinese] 没有issue search的翻译 (Issue #303)




 
你说的是https://github.com/issues吗

**Comment by k1958992420xgd** [comment]
https://github.com/search?q=++bitCount+&amp;type=discussions&amp;p=2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 晚上8:55
收件人: ***@***.***&gt;;
抄送: "zexiang ***@***.******@***.***&gt;;
主题: Re: [maboloshi/github-chinese] 没有issue search的翻译 (Issue #303)




 
截张图上来，以及原链接

**Comment by TC999** [comment]
> https://github.com/search?q=++bitCount+&amp;type=discussions&amp;p=2
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月23日(周六) 晚上8:55 收件人: ***@***.***&gt;; 抄送: "zexiang ***@***.******@***.***&gt;; 主题: Re: [maboloshi/github-chinese] 没有issue search的翻译 (Issue #303) 截张图上来，以及原链接 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个有啊，没有问题

**Comment by k1958992420xgd** [comment]
我怎么感觉我好多页面都没有翻译，是不是我的插件出什么问题了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 晚上10:29
收件人: ***@***.***&gt;;
抄送: "zexiang ***@***.******@***.***&gt;;
主题: Re: [maboloshi/github-chinese] 没有issue search的翻译 (Issue #303)




  
https://github.com/search?q=++bitCount+&amp;amp;type=discussions&amp;amp;p=2
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年11月23日(周六) 晚上8:55 收件人: @.&gt;; 抄送: "zexiang @.@.&gt;; 主题: Re: [maboloshi/github-chinese] 没有issue search的翻译 (Issue #303) 截张图上来，以及原链接 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这个有啊，没有问题

**Comment by TC999** [comment]
你是不是没有更新脚本

**Comment by TC999** [comment]
没翻译的页面去这里说https://github.com/maboloshi/github-chinese/discussions/62
