### ISSUE TITLE
部分仓库中的自述文件README.md中的部分英文原文被错误地替换为中文

### ISSUE THREAD

**Issue by Tommy12pl** [maboloshi/github-chinese#326]
图中的Table of Contents超链接部分的"Download"被错误替换为“下载“
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/a17e741b-3b42-434c-9d76-94f02804bf0b" />

**Comment by TC999** [comment]
发个链接过来，我来看下

**Comment by Tommy12pl** [comment]
> 发个链接过来，我来看下

问题是在这个仓库发现的
https://github.com/BartoszCichecki/LenovoLegionToolkit

**Comment by TC999** [comment]
> > 发个链接过来，我来看下
> 
> 问题是在这个仓库发现的 https://github.com/BartoszCichecki/LenovoLegionToolkit

没更新脚本版本，最新开发版没有此问题

**Comment by maboloshi** [comment]
开发版中已修复

**Comment by Tommy12pl** [comment]
了解了，感谢解答
