### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by FuhaoWaterMelon** [maboloshi/github-chinese#33]
使用“GitHub 中文化插件”时，输入“ ,' ”再退格一次后，英文逗号会变成中文逗号。

**Comment by maboloshi** [comment]
代码编辑页面，代码编辑框？

**Comment by wuyuncheng-26** [comment]
@FuhaoWaterMelon 这个问题应该暂时无法修复

**Comment by maboloshi** [comment]
可能已解决, 请尝试 13f1de0adc5acff8b31405db3cf61b50cddea5b3

**Comment by maboloshi** [comment]
估计已彻底修复 0ed0cf94
