### ISSUE TITLE
部分界面无法翻译

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#44]
@maboloshi 
# 不知道为啥，最近邮件、搜索等界面翻译不了
# 最近才出现的情况
## 我看翻译是没有问题的

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/maboloshi/github-chinese/assets/122529705/1c27ef1d-87e7-4c4d-8eb4-afeaf5902b29)
![image](https://github.com/maboloshi/github-chinese/assets/122529705/d9d8130c-f4ba-4f87-bbe1-254956b82b41)

**Comment by maboloshi** [comment]
```
rePagePath: /^\/(?:users\/[^\/]+\/)(packages)|
```
删掉`(?:users\/[^\/]+\/)(packages)|`
之前引入了bug

**Comment by maboloshi** [comment]
已临时修复 66fbb47

**Comment by wuyuncheng-26** [comment]
👌
