### ISSUE TITLE
正则模式开启情况下的翻译问题

### ISSUE THREAD

**Issue by ZWolken** [maboloshi/github-chinese#5]
当正则模式开启时，已发布的Pre-release内容的描述部分任何单词中包含的 "now" 字符串均会被翻译。（猜测除 "now" 外其他符合条件的内容也会被翻译）
如："Known bugs" 将被翻译为 "K现在n bugs"
正则模式关闭后正常，但关闭后GitHub上将会有许多处内容显示原英文（残念）。

下方为演示截图（[演示仓库预发行版地址](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.1)）
正则模式开启：
<img width="800" alt="1" src="https://user-images.githubusercontent.com/76812845/181591126-648beba7-5a00-4efb-8263-01157cb693c7.png">
正则模式关闭：
<img width="800" alt="2" src="https://user-images.githubusercontent.com/76812845/181591210-57969c2a-ed58-4268-b05a-c065411d2590.png">
中文化插件模块关闭：
<img width="800" alt="3" src="https://user-images.githubusercontent.com/76812845/181591457-0112f0e5-5310-4ad9-878a-431711c2e35b.png">

**Comment by maboloshi** [comment]
"now"的问题 [patch-1](https://github.com/maboloshi/github-chinese/tree/patch-1)分支临时修复, 下个版本会合并

可先安装[patch-1](https://github.com/maboloshi/github-chinese/tree/patch-1)分支下的[main.user.js](https://github.com/maboloshi/github-chinese/blob/patch-1/main.user.js)
