### ISSUE TITLE
翻译再次失效，所有页面都无法翻译

### ISSUE THREAD

**Issue by TC999** [maboloshi/github-chinese#60]
![屏幕截图 2023-11-14 122856](https://github.com/maboloshi/github-chinese/assets/88823709/868ffef2-3a85-48a8-8616-8a846ca2a5c7)
![屏幕截图 2023-11-14 122920](https://github.com/maboloshi/github-chinese/assets/88823709/89ae72c3-1ce1-42be-ae8f-edfe1674ef2a)

**Comment by maboloshi** [comment]
Fix 9826e7e
