### ISSUE TITLE
GitHub Pages 界面有问题

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#61]
![image](https://github.com/maboloshi/github-chinese/assets/122529705/b728b12a-738b-4bb9-8e23-eca265f6d224)
下面的被折到更多里了
应该是 GitHub Pages 对 detail 标签的兼容有问题
可不可以选择换掉 detail 标签？

**Comment by wuyuncheng-26** [comment]
@maboloshi

**Comment by maboloshi** [comment]
暂不处理
