### ISSUE TITLE
建议开发版设置独立版本号以解决自动更新问题

### ISSUE THREAD

**Issue by Zachary-Muadib** [maboloshi/github-chinese#69]

**Comment by maboloshi** [comment]
后期拟打算使用 GitHub actions 定时自动发布

**Comment by wuyuncheng-26** [comment]
现已解决，详情查看 [`f0f557d`](https://github.com/maboloshi/github-chinese/commit/f0f557d668894ce55f8d168a440df01306cf3ba5)

**Comment by wuyuncheng-26** [comment]
@maboloshi 不过好像说 Action 文件内有语法错误

**Comment by maboloshi** [comment]
> @maboloshi 不过好像说 Action 文件内有语法错误

嗯 是的, 等会再排查一下

**Comment by wuyuncheng-26** [comment]
> > @maboloshi 不过好像说 Action 文件内有语法错误
> 
> 嗯 是的, 等会再排查一下

OK，等你

**Comment by maboloshi** [comment]
目前, 还得修改分支保护设置才能提交🤣

**Comment by wuyuncheng-26** [comment]
> 目前, 还得修改分支保护设置才能提交🤣

哈哈哈，那就去掉分支保护吧

**Comment by wuyuncheng-26** [comment]
反正我也不喜欢每次更改都要先 fork，还要提 PR

**Comment by wuyuncheng-26** [comment]
@maboloshi 去掉了应该不会有什么影响吧？

**Comment by maboloshi** [comment]
有, 容易不受控维护

**Comment by wuyuncheng-26** [comment]
> 有, 容易不受控维护

是会被别人删代码吗

**Comment by maboloshi** [comment]
有时候会弄花提交历史

**Comment by wuyuncheng-26** [comment]
> 有时候会弄花提交历史

应该没那么严重吧，反正我没遇到过

**Comment by wuyuncheng-26** [comment]
@maboloshi 大佬搞好了吗

**Comment by maboloshi** [comment]
测试仓库测试通过了

**Comment by wuyuncheng-26** [comment]
> 测试仓库测试通过了

这个？<https://github.com/maboloshi/inuyasha>

**Comment by maboloshi** [comment]
是的
