### ISSUE TITLE
星期的时间现在无法正常翻译

### ISSUE THREAD

**Issue by h88782481** [maboloshi/github-chinese#7]
如题

**Comment by maboloshi** [comment]
请提供示例地址, 我这边本地有修正, 不知你的问题是否能解决.

**Comment by taki-na** [comment]
> 请提供示例地址, 我这边本地有修正, 不知你的问题是否能解决.

![1](https://user-images.githubusercontent.com/80308095/211908549-96488876-4134-4397-a5cd-4d586f07fc5c.png)

**Comment by maboloshi** [comment]
本地已修复 今明我有时间发上来

**Comment by maboloshi** [comment]
已修复 [ebcc97c](https://github.com/maboloshi/github-chinese/commit/ebcc97c16fe47fade3c9f2bf22008e5f98ac7626)
