### ISSUE TITLE
使用`GitHub App`生成的`安装访问令牌`代替`fine-grained PAT`

### ISSUE THREAD

**Issue by maboloshi** [maboloshi/github-chinese#74]
## 参考资料

- [使用 GitHub Actions 工作流中的 GitHub App 发出经过身份验证的 API 请求](https://docs.github.com/zh/apps/creating-github-apps/guides/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow)
- [GitHub Appsトークン解体新書：GitHub ActionsからPATを駆逐する技術](https://zenn.dev/tmknom/articles/github-apps-token)
  - [注册 GitHub 应用](https://docs.github.com/zh/apps/creating-github-apps/registering-a-github-app/registering-a-github-app)
  - [管理 GitHub 应用的私钥](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps)
  - [为 GitHub 应用生成安装访问令牌](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
  - ~~[验证为 GitHub 应用程序安装](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation)~~
  - [为 GitHub 应用生成 JSON Web 令牌 (JWT)](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app)
  - [Get a repository installation for the authenticated app](https://docs.github.com/zh/rest/apps/apps?apiVersion=2022-11-28#get-a-repository-installation-for-the-authenticated-app)
  - [Create an installation access token for an app](https://docs.github.com/zh/rest/apps/apps?apiVrsion=2022-11-28#create-an-installation-access-token-for-an-app)
  - [Revoke an installation access token](https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#revoke-an-installation-access-token)

- ~~[为 GitHub 应用生成用户访问令牌](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)~~
- ~~[代表用户使用 GitHub 应用进行身份验证](https://docs.github.com/zh/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-a-github-app-on-behalf-of-a-user)~~

**Comment by wuyuncheng-26** [comment]
@maboloshi 最近更新了挺多新功能，是不是该弄一个`1.9`版本了？

**Comment by wuyuncheng-26** [comment]
@maboloshi 在吗

**Comment by maboloshi** [comment]
还等几天吧, 手头还有几个半成品没提交

**Comment by maboloshi** [comment]
`GitHub App`的权限不够不能绕过分支保护规则
