### ISSUE TITLE
1.8.0与dark reader 扩展发生冲突，导致时间显示出现问题

### ISSUE THREAD

**Issue by bxmydt** [maboloshi/github-chinese#8]
![image](https://user-images.githubusercontent.com/36289284/213178418-09248065-cfe6-481b-8de3-fa6ffec115e3.png)
![屏幕截图](https://user-images.githubusercontent.com/36289284/213179183-da87f0d6-52b3-4a91-a18a-d52d62f8ef62.png)
平台：win10，edge 109.0.1518.55，firefox 109，dark reader 4.9.62，皆出现此问题，目前的解决方法是将github加入dark reader 的不反色列表。

**Comment by maboloshi** [comment]
github 自带的暗夜主题不能满足需求么

**Comment by maboloshi** [comment]
老版本不存在冲突是吧
另外, 你安装的是github 托管源还是greasyfork 托管源

**Comment by bxmydt** [comment]
> 老版本不存在冲突是吧 另外, 你安装的是 github 托管源还是 greasyfork 托管源

1.7.9的greasyfork 托管源无问题，github托管源有问题。1.8.0的都有问题

**Comment by maboloshi** [comment]
dark reader 是插件还是用户脚本 能否提供链接, 我有时间在研究一下

**Comment by bxmydt** [comment]
> dark reader 是插件还是用户脚本 能否提供链接, 我有时间在研究一下

是插件， https://darkreader.org/ 这是官网，麻烦您了

**Comment by YheonYeung** [comment]
四個鐘前更新，同樣問題。
![image](https://user-images.githubusercontent.com/63342274/213230175-315f752b-4481-4e48-95da-d6757daa90cd.png)

**Comment by ShAlIow** [comment]
![image](https://user-images.githubusercontent.com/99378468/213465922-a7edfba3-b62c-4535-8456-ec920dcdda95.png)
同样问题 找到组织了 好不容易找到自己上个版本备份 自动又给更新掉了

**Comment by maboloshi** [comment]
已修复 1b30071c6473802e19d53601b4494d78c7704ac9
