### ISSUE TITLE
未翻译文本

### ISSUE THREAD

**Issue by fldlqu** [maboloshi/github-chinese#82]
Branch protection rule created.

**Comment by wuyuncheng-26** [comment]
请标明文本出现的链接，以便我们添加

**Comment by fldlqu** [comment]
> 请标明文本出现的链接，以便我们添加

创建分支保护规则时
https://github.com/***/***/settings/branch_protection_rules/new

**Comment by maboloshi** [comment]
开发版的词库已包含, 请重新安装

**Comment by wuyuncheng-26** [comment]
@mixueicecreamandtea 将脚本删除后重新点击文档上的链接以安装

**Comment by wuyuncheng-26** [comment]
这是版本过老的原因
