### ISSUE TITLE
几处翻译的遗漏和错误

### ISSUE THREAD

**Issue by VIKINGYFY** [maboloshi/github-chinese#86]
遗漏：
settings/profile
![image](https://github.com/maboloshi/github-chinese/assets/7755795/e5c1cad1-06c8-4529-b2d4-cea65e581a6a)
billing/summary
很多地方未翻译，截图太多就不发了

仓库/settings
![image](https://github.com/maboloshi/github-chinese/assets/7755795/f81423cc-90e0-48ba-ab67-afe40bfb4124)
![image](https://github.com/maboloshi/github-chinese/assets/7755795/21575bf9-176c-4a6c-8b4d-2ec8b344a45b)

仓库/settings/security_analysis
![image](https://github.com/maboloshi/github-chinese/assets/7755795/76a3e01a-3476-4995-9bc8-0c8af46bf965)

仓库/actions/caches
![image](https://github.com/maboloshi/github-chinese/assets/7755795/5bcb47e5-abae-436f-af7d-3712cf9b79e0)

错误：
工作流中的时间翻译成月份
![image](https://github.com/maboloshi/github-chinese/assets/7755795/4da46718-e141-4b55-a87f-9e6e6ce0b335)
![image](https://github.com/maboloshi/github-chinese/assets/7755795/4d47e2b3-c46e-44a2-be0f-fe66c4101d78)
![image](https://github.com/maboloshi/github-chinese/assets/7755795/ac6aa984-9a60-4ad2-b343-66d0d03204e7)

**Comment by wuyuncheng-26** [comment]
找得还挺细啊

**Comment by wuyuncheng-26** [comment]
现在就修复😘

**Comment by wuyuncheng-26** [comment]
这个已经有了，应该是你版本没更新
![image](https://github.com/maboloshi/github-chinese/assets/122529705/29b6fbfb-bdb5-4c66-83d7-12b594fbb7b3)

**Comment by wuyuncheng-26** [comment]
这个也有了
![image](https://github.com/maboloshi/github-chinese/assets/122529705/2a39e960-e2c9-4f87-b984-86e4e4d8d2ee)

**Comment by maboloshi** [comment]
另外，最近没时间维护 @wuyuncheng-26 
小问题先放放 累计一段时间再说

**Comment by wuyuncheng-26** [comment]
好嘞

**Comment by wuyuncheng-26** [comment]
@maboloshi 您平常只用负责合并就行了

**Comment by wuyuncheng-26** [comment]
@VIKINGYFY 
> 工作流中的时间翻译成月份
详情查看 #10 ，此问题暂时无法修复

**Comment by VIKINGYFY** [comment]
> @VIKINGYFY
> 
> > 工作流中的时间翻译成月份
> 
> 详情查看 #10 ，此问题暂时无法修复

我觉得要不加上网址过滤，检测到actions页面就翻译成分钟或者是直接不翻译？

**Comment by wuyuncheng-26** [comment]
搞定了

**Comment by wuyuncheng-26** [comment]
> > @VIKINGYFY
> > > 工作流中的时间翻译成月份
> > 
> > 
> > 详情查看 #10 ，此问题暂时无法修复
> 
> 我觉得要不加上网址过滤，检测到actions页面就翻译成分钟或者是直接不翻译？

已找到此问题的解决方案
不过目前此功能尚未合并到主分支
可以去 [`Test_zh-CN_LangEnvSet`](https://github.com/maboloshi/github-chinese/tree/Test_zh-CN_LangEnvSet) 分支下的 [`main.user.js`](https://github.com/maboloshi/github-chinese/raw/Test_zh-CN_LangEnvSet/main.user.js) 进行体验
