### ISSUE TITLE
文件编辑时会误转换

### ISSUE THREAD

**Issue by ProjektMing** [maboloshi/github-chinese#89]
在学习编写actions时临时在github 中新建文件添加内容，它会及时地将此时键入的位于 _行首_ 的 `on` 、`1s` 还有 `now` 等（或许存在的）词条转为中文，且暂时试出的结果（仅基于这三个）为：
- 除了 `on` 在行有内容且不仅为空格时行首插入不会变为中文，其他词条均仍会强制转换；
- 当**关闭**正则切换后，仅有 `1s` 不会再被转换；
- 文本中已经存在的这些内容不会被转换。

图例
<img width="541" alt="on 在行首时出现的 bug" src="https://github.com/maboloshi/github-chinese/assets/73031259/298c6793-1e62-4ad6-860d-624e421f7ece">

希望存在的处理办法：为所有输入框禁用转换。
当前版本: 1.9.0及1.9.0-2023-12-16

**Comment by maboloshi** [comment]
把此处注释掉即可, 可能会产生副作用
https://github.com/maboloshi/github-chinese/blob/5be5cee2bda9dd44f98bf8b1e570927b1ed913ea/main.user.js#L81

**Comment by ProjektMing** [comment]
谢谢，现在可以用了。

**Comment by maboloshi** [comment]
如果使用过程中有什么副作用也报上来哈
![Suggestion](https://github.com/maboloshi/github-chinese/assets/7850715/3203f782-cd90-4fb6-b96e-227a6a33141e)

**Comment by maboloshi** [comment]
副作用
<img width="357" alt="image" src="https://github.com/maboloshi/github-chinese/assets/7850715/a98a8d0e-01ef-4d74-93bc-a75a1abd788b">
