### ISSUE TITLE
Safari疑似无效果

### ISSUE THREAD

**Issue by ztm13554800929** [maboloshi/github-chinese#9]
系统版本：macOS Monterey 12.1
浏览器及油猴版本：
Safari 版本15.2 (17612.3.6.1.6) & Tampermonkey 4.17.6162  安装此插件后无效果❌
Microsoft Edge 版本109.0.1518.61 & Tampermonkey 4.16.1  安装此插件后有效果✅

**Comment by maboloshi** [comment]
这个大概率是macos下safari的机制问题 可参考 https://github.com/XIU2/UserScript/issues/107

**Comment by ztm13554800929** [comment]
> 这个大概率是macos下safari的机制问题 可参考 [XIU2/UserScript#107](https://github.com/XIU2/UserScript/issues/107)

嗯嗯，用了Macaque这款插件管理器成功使用了汉化插件，感谢！🙏
