### ISSUE TITLE
[Bug]会在仓库界面将用户名中类似月份等字符翻译

### ISSUE THREAD

**Issue by MengNianxiaoyao** [maboloshi/github-chinese#90]
![image](https://github.com/maboloshi/github-chinese/assets/103258286/7a50c14d-010b-483b-a6a6-bc947abc36be)

**Comment by maboloshi** [comment]
目前有点难, 没有好的特征值

**Comment by wuyuncheng-26** [comment]
这个目前是没有办法的，时间翻译是正则，只要一碰到就翻译

**Comment by MengNianxiaoyao** [comment]
> 这个目前是没有办法的，时间翻译是正则，只要一碰到就翻译

能否将该区域移除正则范围？

**Comment by wuyuncheng-26** [comment]
但是这是仓库首页，移除正则将会出现很多没翻译的情况，所以不能移除
