### ISSUE TITLE
修正一处未翻译处（添加词条失误）

### ISSUE THREAD

**Issue by TC999** [maboloshi/github-chinese#93]
![image](https://github.com/maboloshi/github-chinese/assets/88823709/201164b4-160d-4b6d-8e1c-350200ecc363)
![image](https://github.com/maboloshi/github-chinese/assets/88823709/af351103-8c7e-49a4-9681-f2e83a77f5a9)

如图所示

解决方法：将`locals.js`文件第309行的`"Add a passkey": "添加通行密钥",`改为`"add a passkey": "添加通行密钥",`即可（没注意大小写），代码不知道为什么一直提交失败

**Comment by maboloshi** [comment]
先下拉变基合并到本地,再push

```bash
git pull --rebase --autostash
```

**Comment by maboloshi** [comment]
我来提交吧 顺便我积攒一点也一并 push

**Comment by maboloshi** [comment]
已修正 bad11ea1674858b6742b9d29609c77ac080059aa 请尝试一下

**Comment by TC999** [comment]
> 已修正 [bad11ea](https://github.com/maboloshi/github-chinese/commit/bad11ea1674858b6742b9d29609c77ac080059aa) 请尝试一下

![image](https://github.com/maboloshi/github-chinese/assets/88823709/bcbdd5fa-b22b-4419-b499-19ace173ada8)
可正常显示
