### ISSUE TITLE
项目界面翻译失败

### ISSUE THREAD

**Issue by wuyuncheng-26** [maboloshi/github-chinese#98]
@maboloshi 
<https://github.com/users/user-name/projects/id>
![image](https://github.com/maboloshi/github-chinese/assets/122529705/b7eb5ac4-b585-4248-8c41-374283144015)
看代码里是有翻译的，应该是没有这个网页的翻译设置
可能要在`rePagePath`里添加一下

**Comment by maboloshi** [comment]
目前有意避开`project`相关页面

**Comment by wuyuncheng-26** [comment]
> 目前有意避开`project`相关页面

为啥呢

**Comment by maboloshi** [comment]
1. 自己很少用
2. 有段时间 UI 更新太频繁 懒得适配

**Comment by maboloshi** [comment]
Fix(4eb442add7578ac2d07488fa90d3da9916560a9d)，可以匹配`/users/<username>/projects`了

目前，项目的词条只适配旧版经典项目
欢迎有需要的伙伴了来PR
